name = "Veld"
grammar = "tree-sitter-veld"
path_suffixes = ["veld"]
line_comments = ["# "]

[indent]
tab_size = 4
unit = "    "

# [brackets]
# pairs = [
#     { start = "{", end = "}" },
#     { start = "[", end = "]" },
#     { start = "(", end = ")" },
# ]

# [code_actions]
# surrounding_pairs = [
#     { start = "{", end = "}" },
#     { start = "[", end = "]" },
#     { start = "(", end = ")" },
#     { start = "\"", end = "\"" },
#     { start = "'", end = "'" },
# ]
